version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'mymongo'
    environment:
      - MONGO_INITDB_DATABASE=mydb
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
    - ./mongo-volume:/data/db

    ports:
    - '27017-27019:27017-27019'
